function chooseSetOfParameters
    
    parameters_all = getappdata(0, 'parameters') ;
    if length(fieldnames(parameters_all)) == 1
        warndlg('Only one set of parameters defined.')
        return ;
    end
    data = cell(0) ;
    for iSet = fieldnames(parameters_all)'
        data = cat(2, data, num2cell(str2double(struct2cell(parameters_all.(char(iSet)))))) ;
    end
        
    cnames = fieldnames(parameters_all)' ;
    rnames = fieldnames(parameters_all.(char(cnames{1})))' ;

    f = figure('Name', 'CHOOSE SET',...
               'Menubar', 'none',...
               'Units', 'normalized',...
               'Position', [0.3, 0.4, 0.25, 0.2]) ;
    
    tab_zones = uitable('Parent'    , f,...
                        'Units'     , 'normalized',...
                        'Position'  , [0.1, 0.2, 0.8, 0.7],...
                        'Data'      , data,...
                        'ColumnName', cnames,...
                        'RowName'   , rnames) ;

    h1 = uicontrol('Style'          , 'text',...
                   'Units'          , 'normalized',...
                   'Position'       , [0.1, 0.1, 0.35, 0.1],...
                   'String'         , 'Choose index of set:',...
                   'FontSize'       , 8,...
                   'FontWeight'     , 'bold',...
                   'BackgroundColor', 'white') ;
    
    h2 = uicontrol('Style'          , 'edit',...
                   'Units'          , 'normalized',...
                   'Position'       , [0.5, 0.1, 0.2, 0.1],...
                   'String'         , '1',...
                   'BackgroundColor', 'white') ;
    
    h3 = uicontrol('Style'   , 'pushbutton',...
                   'Units'   , 'normalized',...
                   'Position', [0.75, 0.1, 0.2, 0.1],...
                   'String'  , 'Choose',...
                   'Callback', {@saveClose, h2}) ;

function saveClose(src, evt, h2)
    global SET ;
    switch str2double(get(h2, 'String'))
    case 1
        SET = 'user' ;
    otherwise
        SET = ['set', char(double(get(h2, 'String')-1))] ;
    end
    close ;