function trialDesign(hObject)

    handles = guidata(hObject) ;

f = figure('NumberTitle', 'off', 'Name', 'Stimuli properties', 'Menubar', 'none') ;
    set(f, 'Units', 'normalized', 'Position', [0.2, 0.3, 0.6, 0.1]) ;
    cnames = cell(0) ;
    nb_cond = str2num(handles.parameters_user.nb_cond) ;
    for iCond = 1:nb_cond
        cnames = cat(2, cnames, ['Stimulus ', num2str(iCond)]) ;
    end
    data = repmat({[]}, 1, 7) ;
    rnames = {'Frequency (in Hz) of the stimulus'} ;
    column_editable = [true(1, nb_cond)] ;
    tab_zones = uitable('Parent', f,...
                        'Units', 'normalized',...
                        'FontWeight', 'demi',...
                        'Enable', 'on',...
                        'Position', [0, 0, 1, 1],...
                        'Data', cell(data),...
                        'ColumnName', cnames,...
                        'ColumnEditable', column_editable,...
                        'RowName', rnames,...
                        'ColumnWidth', 'auto') ;

    handles_u = uicontrol('Parent', f,...
                          'Units', 'normalized',...
                          'Position', [0.5, 0.2, 0.1, 0.2],...
                          'Style', 'pushbutton',...
                          'String', 'Save & Close',...
                          'Callback', {@getFeatures, nb_cond, tab_zones}) ;

    guidata(hObject, handles) ;